######################## default configuration ####################
baseURL = "https://00000000014A6343.pages.gitlab.lrz.de/alumni-network"
title = "STS-Munich.de"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # disable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Impressum"
URL = "impressum"
weight = 3

# [[menu.main]]
# name = "Contact"
# URL = "contact"
# weight = 4

# [[menu.main]]
# name = "Sample Page"
# URL = "sample-page"
# weight = 5

# only desktop menu
[[menu.desktop]]
name = "Our Roadmap"
URL = "/about"
weight = 1


#################### default parameters ################################
[params]
# Meta data
description = "Getting the MCTS Alumni Network started."
author = "Matthias Meller"

# cookies
[params.cookies]
enable = false
expire_days = 2

# banner
[params.banner]
heading = "MCTS Alumni Network initiative has started!"
image = "images/title-image-zoom-christmas.png"

# blog
[params.blog]
heading = "We believe students, PhDs and alumni of the Munich Center for Technology in Society need a space to connect beyond university and to bring the best of STS into the world. </br> </br> <b style='color:#0076bb'>Let's create our alumni network together.</b>"

# call to action
[params.call_to_action]
enable = true
title = "Join our virtual MCTS Christmas Party on Dec 18"
content = "No, not another Zoom call, but an entire online Christmas Party venue just for us! Even though we can't enjoy GlÃ¼hwein or Punsch in person this year, together with the staff of MCTS, we're hosting a <b>virtual Christmas Party</b>.<br><br>Join us starting from 7:30 pm for conversations, fun activities or games. Decorate your desks at home, prepare snacks, drinks â€” we'll see us online!<br><br><i>We're using the tool <a href='https://wonder.me'>wonder.me</a>, a Germany-based tool for creating virtual meeting spaces. Please review its <a href='https://www.wonder.me/privacy-policy'>privacy policy</a> (and <a href='https://support.wonder.me/hc/en-us/articles/360013622577-Privacy-Security-FAQs'>FAQ</a>) prior to joining.</i>"
button_label = "ðŸŽ„ Join The Party ðŸŽ„"
button_url = "https://www.wonder.me/r?id=02418b2b-e994-4a0c-85b8-dc060e700347"

# gallery
[params.gallery]
enable = false

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"


# footer
[params.footer]
title = "Join the Project Team"
content = "We want to establish the Alumni Network by March 2021 as legal association (<i>eingetragender Verein - e.V.</i>). Whether it's legal, future activities or communication, there are lots of ways to contribute (<a href='/alumni-network/about'>check our roadmap here</a>)<br><br><b>Join us!</b> Write us at <a href='mailto:alumni-network@mcts.tum.de'>alumni-network@mcts.tum.de</a> and you'll be invited to our Slack Workspace."
address = "Virtual Christmas Party @ 7:30 pm via <a href='https://www.wonder.me/r?id=02418b2b-e994-4a0c-85b8-dc060e700347'>wonder.me</a>"
# hours = "Mondayâ€“Friday: 9:00AMâ€“5:00PM <br> Saturday & Sunday: 11:00AMâ€“3:00PM"
copyright = "&copy; 2020. Made with [Hugo](https://gohugo.io), [Twenty Twenty Theme](https://themes.gohugo.io/twenty-twenty-hugo/) and much â™¥ï¸Ž from Munich."

############################# social site ########################
[params.social]
# yelp = "#"
# facebook = "#"
# twitter = "#"
# instagram = "#"
email = "alumni-network@mcts.tum.de"
# linkedin = "#"